modLoader="javafml"
loaderVersion="[37,)"
#updateJSONURL="http://myurl.me/"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="gigaherz"
license="BSD (3 clause)"

[[mods]]
modId="toolbelt"
version="${file.jarVersion}"
displayName="Tool Belt"
description='''
Declutter your inventory of tools
'''
issueTrackerURL="https://github.com/gigaherz/ToolBelt/issues"
displayURL="https://github.com/gigaherz/ToolBelt"

[[dependencies.toolbelt]]
   modId="forge"
   mandatory=true
   versionRange="[37.0.29,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.toolbelt]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.17.1,1.18)"
   ordering="NONE"
   side="BOTH"
[[dependencies.toolbelt]]
   modId="sewingkit"
   mandatory=false
   versionRange="[1.1,)"
   ordering="NONE"
   side="BOTH"